OPENAI_API_KEY:
  description: "OpenAI API Key"
  required: true
OPENAI_BASE_URL:
  description: "OpenAI Base URL"
  default: "https://api.deepseek.com/v1"
OPENAI_MODEL:
  description: "OpenAI Model"
  default: "deepseek-chat"
ENABLE_DEBUG:
  description: "enable debug"
  default: false
FASTCOMMIT_GEN_VERSION:
  description: "git commit gen version"
  default: false
